---
# A test case to install, configure containers (do not run it),
# then to check a virtqemud container config
tripleo_nova_libvirt_config_keep_container: true
config:
  - name: /etc/libvirt/virtqemud.conf
    container: nova_libvirt_config
    expected_lines:
      - unix_sock_group = 'libvirt'
      - unix_sock_ro_perms = '0444'
      - unix_sock_rw_perms = '0770'
      - auth_unix_ro = 'none'
      - auth_unix_rw = 'none'
      - log_filters = '1:qemu 1:libvirt 4:object 4:json 4:event 1:util'
      - log_outputs = '1:file:/var/log/libvirt/virtqemud.log'
molecule_tags_enforce: false
test_tags:
  - install
  - configure
test_skip_tags:
  - run
